const mongoose = require('mongoose');

const CampaignSchema = new mongoose.Schema(
  {
    'Campaign Short Desc': { type: String, trim: true },
    'Recall Number': { type: String, trim: true },
    'Campaign description': { type: String, trim: true },
    'External Number': { type: String, trim: true },
    'Start Date': { type: Date, default: null },
    'End Date': { type: Date, default: null },
    'Chasis Number': { type: String, trim: true },
    'Job Card Number': { type: String, trim: true, default: null },
    'Job Card Created Date': { type: Date, default: null },
    'PDI Dealer Code': { type: mongoose.Schema.Types.Mixed, default: null },
    'PDI Dealer Name': { type: String, trim: true },
    'PDI Dealer City': { type: String, trim: true },
    'PDI Dealer State': { type: String, trim: true },
    'PDI Dealer Region': { type: String, trim: true },
    'Selling Dealer Code': { type: mongoose.Schema.Types.Mixed, default: null },
    'Selling Dealer Name': { type: String, trim: true },
    'Selling Dealer City': { type: String, trim: true },
    'Selling Dealer State': { type: String, trim: true },
    'Selling Dealer Region': { type: String, trim: true },
    'km/hr': { type: Number, default: null },
    'Campaign Status': { type: String, trim: true },
    'Claim Number': { type: String, trim: true },
    'Claim Date': { type: Date, default: null },
    'Claim Status': { type: String, trim: true },
    'Dealer Code': mongoose.Schema.Types.Mixed,
    'Dealer': { type: String, trim: true },
    'Dealer City': { type: String, trim: true },
    'State': { type: String, trim: true },
    'Region': { type: String, trim: true },
    'Segment': { type: String, trim: true },
    'Model -ID': { type: String, trim: true },
    'Model-Description': { type: String, trim: true },
    'BS Norms': { type: String, trim: true },
    'Series': { type: String, trim: true },
    'Assigned Dealer Code': { type: mongoose.Schema.Types.Mixed, default: null },
    'Assigned Dealer Name': { type: String, trim: true },
    'Assigned Region': { type: String, trim: true },
    'Assigned Area Office': { type: String, trim: true },
    'Customer Name': { type: String, trim: true },
    'Regi No': { type: mongoose.Schema.Types.Mixed, default: null },
    'Segment_1': { type: String, trim: true, default: null },
    'Dealer 1S Code': { type: mongoose.Schema.Types.Mixed, default: null },
    'Vehicle Segment': { type: String, trim: true, default: null },
    'Fuel Type': { type: String, trim: true, default: null },
    'ODO Range': { type: String, trim: true, default: null },
    'Year in failure': { type: String, trim: true, default: null },
    'CULPRIT CODE': { type: String, trim: true, default: null },
    'Culprit Desc.': { type: String, trim: true, default: null },
    'Part L1': { type: String, trim: true, default: null },
    'Part Desc.': { type: String, trim: true, default: null },
    'Total Amount': { type: Number, default: null },
    'U2H2': { type: String, trim: true },
    'Company Code': { type: String, trim: true },
    'Plant Code': { type: String, trim: true },
    'Campaign Type': { type: String, trim: true },
  },
  { timestamps: true, strict: false, versionKey: false }
);

module.exports = mongoose.model('Campaign', CampaignSchema);
